### ISSUE TITLE
createTransaction always removes connection from pool

### ISSUE THREAD

**Issue by danneu** [epochtalk/core-pg#21]
The source in question: https://github.com/epochtalk/core-pg/blob/94cfacd4fefd36325f9ef2a6f03f4866010f483f/db.js#L40-L47

``` javascript
.disposer(function(client, promise) {
  function closeConnection() { if (close) { close(client); } }

  if (promise.isFulfilled()) {
    return client.queryAsync('COMMIT').then(closeConnection);
  }
  else {
    return client.queryAsync('ROLLBACK').then(closeConnection);
  }
});
```

It looks like `client` is always going to be a truthy value here, and passing a truthy value into `close(truthy)` is how you remove a connection from the pool whereas `close()` releases the connection back into the pool for reuse.

As I understand this code, the connection will always be removed from the pool after successful COMMIT or successful ROLLBACK. Instead, those two cases should always call `close()` to release the connection since the connection is in a good state (committed or rolled back).

However, ROLLBACK can fail. If ROLLBACK fails, then the connection is mid-transaction and it's *then* that it needs to be nuked from the pool with `close(truthy)`. Since the current code doesn't handle ROLLBACK failure, it will leak a bad connection instead of nuking it.

I have a Node+Postgres forum running in production that attempts a similar abstraction: https://github.com/danneu/guild/blob/7506221c6004d5147c9139828242dc5459ee8a07/server/db.js#L97

**Comment by taesup** [comment]
Good catch! It looks like the docs for bluebird have changed since I wrote that. I'll go update it now.

**Comment by taesup** [comment]
Tried to handle this issue in commit 73cb462d246f37ec3428c91dad769e8a8b786eec.
Let me know what you think.

**Comment by taesup** [comment]
@danneu ^

**Comment by wangbus** [comment]
@danneu: Thanks for the issue dude!

**Comment by danneu** [comment]
@taesup, @wangbus: The `if (close)` and `if (err)` checks seem extraneous to me at a glance, but otherwise it looks good.
